import type { Product, Category } from '@/types';

export const mockCategories: Category[] = [
  { id: '1', name: 'Women', slug: 'women', image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400' },
  { id: '2', name: 'Men', slug: 'men', image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400' },
  { id: '3', name: 'Kids', slug: 'kids', image: 'https://images.unsplash.com/photo-1503919005314-30d93d07d823?w=400' },
  { id: '4', name: 'Beauty', slug: 'beauty', image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400' },
  { id: '5', name: 'Home & Living', slug: 'home-living', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400' },
  { id: '6', name: 'Sport', slug: 'sport', image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400' },
];

const womenCategory: Category = { id: '1', name: 'Women', slug: 'women' };
const menCategory: Category = { id: '2', name: 'Men', slug: 'men' };

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Floral Print Wrap Dress',
    slug: 'floral-print-wrap-dress',
    description: 'A beautiful floral wrap dress perfect for summer occasions. Made with lightweight chiffon fabric.',
    price: 2499,
    discountPrice: 1499,
    stock: 50,
    sku: 'WD001',
    brand: 'H&M',
    category: womenCategory,
    images: [
      { id: '1', url: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268217?w=600', alt: 'Floral Dress', isPrimary: true },
      { id: '2', url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600', alt: 'Floral Dress Back', isPrimary: false },
    ],
    tags: ['dress', 'floral', 'summer'],
    isFeatured: true,
    isActive: true,
    averageRating: 4.3,
    reviewCount: 128,
  },
  {
    id: '2',
    name: 'Classic Slim Fit Jeans',
    slug: 'classic-slim-fit-jeans',
    description: 'Timeless slim fit jeans crafted from premium denim. Features five pockets and a comfortable stretch.',
    price: 3999,
    discountPrice: 2799,
    stock: 75,
    sku: 'MJ001',
    brand: "Levi's",
    category: menCategory,
    images: [
      { id: '3', url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600', alt: 'Slim Fit Jeans', isPrimary: true },
      { id: '4', url: 'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=600', alt: 'Jeans Detail', isPrimary: false },
    ],
    tags: ['jeans', 'denim', 'casual'],
    isFeatured: true,
    isActive: true,
    averageRating: 4.5,
    reviewCount: 312,
  },
  {
    id: '3',
    name: 'Oversized Graphic Tee',
    slug: 'oversized-graphic-tee',
    description: 'Trendy oversized graphic tee made from 100% cotton. Perfect for casual outings.',
    price: 999,
    discountPrice: 599,
    stock: 100,
    sku: 'WT001',
    brand: 'Roadster',
    category: womenCategory,
    images: [
      { id: '5', url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600', alt: 'Graphic Tee', isPrimary: true },
    ],
    tags: ['tshirt', 'graphic', 'casual', 'cotton'],
    isFeatured: true,
    isActive: true,
    averageRating: 4.1,
    reviewCount: 89,
  },
  {
    id: '4',
    name: 'Formal Slim Fit Shirt',
    slug: 'formal-slim-fit-shirt',
    description: 'Elegant slim fit formal shirt for the modern professional. Available in multiple colors.',
    price: 1999,
    discountPrice: 1299,
    stock: 60,
    sku: 'MS001',
    brand: 'Arrow',
    category: menCategory,
    images: [
      { id: '6', url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600', alt: 'Formal Shirt', isPrimary: true },
    ],
    tags: ['shirt', 'formal', 'office'],
    isFeatured: true,
    isActive: true,
    averageRating: 4.4,
    reviewCount: 156,
  },
  {
    id: '5',
    name: 'Embroidered Anarkali Kurta',
    slug: 'embroidered-anarkali-kurta',
    description: 'Stunning embroidered Anarkali kurta with intricate handwork. Perfect for festivals and celebrations.',
    price: 4999,
    discountPrice: 3499,
    stock: 30,
    sku: 'WK001',
    brand: 'Biba',
    category: womenCategory,
    images: [
      { id: '7', url: 'https://images.unsplash.com/photo-1583391733956-62e7d8f7d1c0?w=600', alt: 'Anarkali Kurta', isPrimary: true },
    ],
    tags: ['kurta', 'ethnic', 'festival', 'embroidered'],
    isFeatured: true,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 203,
  },
  {
    id: '6',
    name: 'Running Sports Shoes',
    slug: 'running-sports-shoes',
    description: 'High-performance running shoes with advanced cushioning technology and breathable mesh upper.',
    price: 5999,
    discountPrice: 4499,
    stock: 45,
    sku: 'SS001',
    brand: 'Nike',
    category: menCategory,
    images: [
      { id: '8', url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600', alt: 'Running Shoes', isPrimary: true },
    ],
    tags: ['shoes', 'running', 'sports', 'athletic'],
    isFeatured: true,
    isActive: true,
    averageRating: 4.6,
    reviewCount: 445,
  },
  {
    id: '7',
    name: 'Pleated Mini Skirt',
    slug: 'pleated-mini-skirt',
    description: 'Chic pleated mini skirt in solid colors. Pairs perfectly with crop tops and tees.',
    price: 1499,
    discountPrice: 899,
    stock: 80,
    sku: 'WS001',
    brand: 'Zara',
    category: womenCategory,
    images: [
      { id: '9', url: 'https://images.unsplash.com/photo-1583496661160-fb5218ee50f4?w=600', alt: 'Mini Skirt', isPrimary: true },
    ],
    tags: ['skirt', 'mini', 'casual', 'trendy'],
    isFeatured: false,
    isActive: true,
    averageRating: 4.2,
    reviewCount: 67,
  },
  {
    id: '8',
    name: 'Hooded Sweatshirt',
    slug: 'hooded-sweatshirt',
    description: 'Cozy hooded sweatshirt for those cool evenings. Fleece-lined interior for extra warmth.',
    price: 2499,
    discountPrice: 1799,
    stock: 90,
    sku: 'MH001',
    brand: 'HRX',
    category: menCategory,
    images: [
      { id: '10', url: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600', alt: 'Hooded Sweatshirt', isPrimary: true },
    ],
    tags: ['hoodie', 'sweatshirt', 'casual', 'winter'],
    isFeatured: false,
    isActive: true,
    averageRating: 4.3,
    reviewCount: 178,
  },
];

export const featuredProducts = mockProducts.filter((p) => p.isFeatured);
